export CUDA_VISIBLE_DEVICES=1

model_name=MIDAPN

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/ljr/raw_files/weather/ \
  --data_path weather.csv\
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --layers 1 \
  --num_clusters 64 \
  --id_dim 8 \
  --cluster_dim 8 \
  --graph_dim 32 \
  --d_model 512 \
  --enc_in 21 \
  --batch_size 16 \
  --learning_rate 0.001 \
  --des 'Exp' \
  --train_epochs 10 \
  --patience 5 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/ljr/raw_files/weather/ \
  --data_path weather.csv\
  --model_id weather_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --layers 1 \
  --num_clusters 64 \
  --id_dim 8 \
  --cluster_dim 8 \
  --graph_dim 32 \
  --d_model 512 \
  --enc_in 21 \
  --batch_size 16 \
  --learning_rate 0.001 \
  --des 'Exp' \
  --train_epochs 10 \
  --patience 5 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/ljr/raw_files/weather/ \
  --data_path weather.csv\
  --model_id weather_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --layers 1 \
  --num_clusters 64 \
  --id_dim 8 \
  --cluster_dim 8 \
  --graph_dim 32 \
  --d_model 512 \
  --enc_in 21 \
  --batch_size 16 \
  --learning_rate 0.0003 \
  --des 'Exp' \
  --train_epochs 10 \
  --patience 5 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path /home/ljr/raw_files/weather/ \
  --data_path weather.csv\
  --model_id weather_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --layers 1 \
  --num_clusters 64 \
  --id_dim 8 \
  --cluster_dim 8 \
  --graph_dim 32 \
  --d_model 512 \
  --enc_in 21 \
  --batch_size 16 \
  --learning_rate 0.001 \
  --des 'Exp' \
  --train_epochs 10 \
  --patience 5 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \
