export CUDA_VISIBLE_DEVICES=0

model_name=MIDAPN_t
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./raw_files/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --layers 3 \
  --num_clusters 64 \
  --id_dim 32 \
  --cluster_dim 16 \
  --graph_dim 64 \
  --d_model 512 \
  --enc_in 862 \
  --batch_size 16 \
  --learning_rate 0.0005 \
  --des 'Exp' \
  --train_epochs 70 \
  --patience 15 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \
  --lradj cosine
  
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./raw_files/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --layers 3 \
  --num_clusters 64 \
  --id_dim 32 \
  --cluster_dim 16 \
  --graph_dim 64 \
  --d_model 512 \
  --enc_in 862 \
  --batch_size 16 \
  --learning_rate 0.0005 \
  --des 'Exp' \
  --train_epochs 70 \
  --patience 15 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \
  --lradj cosine

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./raw_files/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --layers 3 \
  --num_clusters 64 \
  --id_dim 32 \
  --cluster_dim 16 \
  --graph_dim 64 \
  --d_model 512 \
  --enc_in 862 \
  --batch_size 16 \
  --learning_rate 0.0005 \
  --des 'Exp' \
  --train_epochs 70 \
  --patience 15 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \
  --lradj cosine

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./raw_files/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --layers 3 \
  --num_clusters 64 \
  --id_dim 32 \
  --cluster_dim 16 \
  --graph_dim 64 \
  --d_model 512 \
  --enc_in 862 \
  --batch_size 16 \
  --learning_rate 0.0005 \
  --des 'Exp' \
  --train_epochs 100 \
  --patience 15 \
  --itr 1 \
  --gpu 0 \
  --loss 'MAE' \
  --lradj cosine
